repos:
  -
    repo: 'https://github.com/ambv/black'
    rev: 18.9b0
    hooks:
      -
        id: black
        language_version: python3.6
  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.1.0
    hooks:
      -
        id: flake8
        language_version: python3.6
        additional_dependencies:
          - flake8-bandit
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-isort
          - flake8-quotes
          - flake8-string-format
          - pep8-naming
  -
    repo: local
    hooks:
      -
        id: mypy
        name: 'mypy'
        entry: 'mypy --strict strava_flow'
        pass_filenames: false
        language: system
        types:
          - python
